services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    restart: always

  app:
    build: .
    container_name: teamscal-app
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    restart: always
